{
   "before_install" : "true",
   "env" : {
      "global" : {
         "secure" : "YcefY13rBWdF4n34Fi8h90h4tipu3HqvvuGT\u002BxCJbSk4zBGlr7ybNsKwm3bjrI5yWFHszLNTyos78Z\u002BRQJpJY1EjKhclwlJbH5xL7wR9FB0dJ65gbbrTWjvat110o4amG1kswNhQwGbDH9Jbp27HMBXn5RAu5eYdlolPM8vUZOYYHIwCyp3ckevtTtpExQEr6evi58Ebx7VTtlqwFwN8aA3wHXmE8x2ub/5P3z4AeVsTd4AaIQez7egcgCf6D4HSUXuy2zwDOLH0x6cw4aDplLWYstce7xEaNJXmwmZH2p6mJL6QK3KlGN8Mybo8XG6Q9BR7WDXr0jVNuEj1TG\u002Bjg2BQ8eypFbHhkljk2uH9MpelgJYxV5ngqGZkZwOqoEd1TxOvKtuRI38kli8G20smLAeL2Mo8tKeNyeCPx6irQmCCU1oe3BwMwzw74fdIX3O8IHYUcS8zb8vctJ6FJU8Va\u002Br43lfytdhL1vEmNBmHo/2PUimYC7gj0mePEP9rxCZMxbk1FKTdYBB\u002B6YPtGIEwGiSKFV32y3xtYqfwPBhDBS5fAcTMidkDiM510a/88fEEi3WuQm\u002BTWfj1epexm\u002BoXwWdsSw9gd1UOuoX\u002BAcrMHF9rvMNJ0OesBKOXf9K4Q1wcnhFJQb0vILZLpEGtC2X4awwS6uUG4gbytmujb740Asc="
      }
   },
   "git" : {
      "submodules" : false
   },
   "install" : "make test-deps",
   "jobs" : {
      "include" : [
         {
            "stage" : "test"
         },
         {
            "before_install" : "true",
            "install" : "true",
            "script" : "curl -f https://gist.githubusercontent.com/wakaba/ab553f86cd017e0cb28c6dbb5364b009/raw/travis-merge-job.pl | perl",
            "stage" : "merge"
         }
      ]
   },
   "language" : "perl",
   "perl" : [
      "5.32",
      "5.14"
   ],
   "script" : "make test"
}
