{
   "before_install" : "true",
   "git" : {
      "submodules" : false
   },
   "install" : "make test-deps",
   "jobs" : {
      "include" : [
         {
            "stage" : "test"
         }
      ]
   },
   "language" : "perl",
   "perl" : [
      "5.26",
      "5.14"
   ],
   "script" : "make test"
}
